use failure::Error;

pub fn main() -> Result<(), Error> {
    Ok(())
}
